Write-Output "Configuring $fsxDirFlight Simulator X for use with ControllerBuddy-Profiles...`n"

$fsxDir = "$env:APPDATA\Microsoft\FSX"

if (-not (Test-Path $fsxDir -PathType Container)) {
    Write-Output "Error: $fsxDirFlight Simulator X config directory '$fsxDir' does not exist"
    Exit 1
}

Import-Module -Name "$PSScriptRoot\..\.lib\DirectInput"

$vJoyDevice = Get-VJoyDevice

if ($null -eq $vJoyDevice) {
    Write-Output 'Error: Could not find vJoy device'
    Exit 1
}

$gamepadDevices = Get-GamepadDeviceList

if (-not (Test-Path -Path 'HKCU:\Software\Wine')) {
    while ($gamepadDevices.Count -lt 1) {
        Add-Type -AssemblyName PresentationCore, PresentationFramework

        if ([System.Windows.MessageBox]::Show("There is currently no controller connected.`nTo retry, please connect your controller now.`n`nRetry?", 'No controller connected', [System.Windows.MessageBoxButton]::YesNo, [System.Windows.MessageBoxImage]::Warning) -ne [System.Windows.MessageBoxResult]::Yes) {
            Write-Output 'Error: No controller connected'
            Exit 1
        }

        $gamepadDevices = Get-GamepadDeviceList
    }
}

function Get-DeviceGuid {
    param (
        [Parameter(Mandatory = $true)]
        [object]$Device
    )

    $Device.InstanceGuid.ToString().ToUpper()
}

try {
    $standardXmlFile = "$fsxDir\Controls\Standard.XML"
    $vJoyDeviceGuid = Get-DeviceGuid $vJoyDevice
    $standardXmlContent = @"
<?xml version="1.0" encoding="Windows-1252"?>

<SimBase.Document
        Type="Controls"
        version="1,0"
        id="Standard">
    <Descr>Controls Mapping File</Descr>
    <Filename>Standard.XML</Filename>
    <SimControls.Map>
        <Name>KEYBOARD_MAIN</Name>
        <Entry>
            <Key>SHIFT+F10</Key>
            <Down>KNEEBOARD_VIEW</Down>
        </Entry>
        <Entry>
            <Key>CTRL+S</Key>
            <Down>VIEW_PREVIOUS_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>G</Key>
            <Down>GEAR_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>VK_LBRACKET</Key>
            <Down>NEW_VIEW</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+T</Key>
            <Down>MP_TRANSFER_CONTROL</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+F</Key>
            <Down>REQUEST_FUEL_KEY</Down>
        </Entry>
        <Entry>
            <Key>CTRL+F3</Key>
            <Down>PROP_PITCH_INCR_SMALL</Down>
        </Entry>
        <Entry>
            <Key>CTRL+G</Key>
            <Down>GEAR_PUMP</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_6+Num_5</Key>
            <Down>VIEW_RIGHT_UP</Down>
            <Up>VIEW_RIGHT_UP</Up>
        </Entry>
        <Entry>
            <Key>VK_QUOTE</Key>
            <Down>VIEW_WINDOW_TO_FRONT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+X</Key>
            <Down>VIRTUAL_COPILOT_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+C</Key>
            <Down>EXIT</Down>
        </Entry>
        <Entry>
            <Key>V</Key>
            <Down>CAPTURE_SCREENSHOT</Down>
        </Entry>
        <Entry>
            <Key>Num_7</Key>
            <Down>ELEV_TRIM_DN</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+V</Key>
            <Down>INC_COWL_FLAPS</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Y</Key>
            <Down>TOW_PLANE_RELEASE</Down>
        </Entry>
        <Entry>
            <Key>M</Key>
            <Down>MAGNETO</Down>
        </Entry>
        <Entry>
            <Key>CTRL+2</Key>
            <Down>RADIO_VOR2_IDENT_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Enter</Key>
            <Down>EYEPOINT_BACK</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+Num_6</Key>
            <Down>LANDING_LIGHT_RIGHT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+F3</Key>
            <Down>MIXTURE_INCR_SMALL</Down>
        </Entry>
        <Entry>
            <Key>CTRL+VK_PERIOD</Key>
            <Down>PARKING_BRAKES</Down>
        </Entry>
        <Entry>
            <Key>A</Key>
            <Down>NEXT_SUB_VIEW</Down>
        </Entry>
        <Entry>
            <Key>Num_1</Key>
            <Down>ELEV_TRIM_UP</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+Tab</Key>
            <Down>PREV_VIEW</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+F</Key>
            <Down>MP_PLAYER_FOLLOW</Down>
        </Entry>
        <Entry>
            <Key>Backspace</Key>
            <Down>ZOOM_1X</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+U</Key>
            <Down>AUTORUDDER_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+M</Key>
            <Down>AP_MACH_HOLD</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+I</Key>
            <Down>TAKEOFF_ASSIST_ARM_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+R</Key>
            <Down>AUTO_THROTTLE_ARM</Down>
        </Entry>
        <Entry>
            <Key>CTRL+VK_LBRACKET</Key>
            <Down>SCRIPT_EVENT_1</Down>
        </Entry>
        <Entry>
            <Key>CTRL+VK_RBRACKET</Key>
            <Down>SCRIPT_EVENT_2</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_4+Num_5</Key>
            <Down>VIEW_LEFT_UP</Down>
            <Up>VIEW_LEFT_UP</Up>
        </Entry>
        <Entry>
            <Key>Space</Key>
            <Down>MOUSE_LOOK_TOGGLE</Down>
            <DownVal>1</DownVal>
            <Up>MOUSE_LOOK_TOGGLE</Up>
            <UpVal>2</UpVal>
        </Entry>
        <Entry>
            <Key>SHIFT+O</Key>
            <Down>MOUSE_LOOK_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>VK_MULTIPLY</Key>
            <Down>BRAKES_LEFT</Down>
        </Entry>
        <Entry>
            <Key>VK_SEMICOLON</Key>
            <Down>SITUATION_SAVE</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+S</Key>
            <Down>VIEW_MODE_REV</Down>
        </Entry>
        <Entry>
            <Key>E</Key>
            <Down>ENGINE</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Caps_Lock</Key>
            <Down>MP_BROADCAST_VOICE_CAPTURE_START</Down>
            <Up>MP_BROADCAST_VOICE_CAPTURE_STOP</Up>
        </Entry>
        <Entry>
            <Key>CTRL+W</Key>
            <Down>TOGGLE_WATER_RUDDER</Down>
        </Entry>
        <Entry>
            <Key>I</Key>
            <Down>SMOKE_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+Backspace</Key>
            <Down>EYEPOINT_LEFT</Down>
        </Entry>
        <Entry>
            <Key>Y</Key>
            <Down>SLEW_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>J</Key>
            <Down>HOIST_SWITCH_EXTEND</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+G</Key>
            <Down>TOGGLE_TAILWHEEL_LOCK</Down>
        </Entry>
        <Entry>
            <Key>CTRL+F24</Key>
            <Down>RUDDER_TRIM_RIGHT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Num_8</Key>
            <Down>VIEW_FORWARD_UP</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_8+Num_5</Key>
            <Down>VIEW_FORWARD_UP</Down>
            <Up>VIEW_FORWARD_UP</Up>
        </Entry>
        <Entry>
            <Key>VK_MINUS</Key>
            <Down>MINUS</Down>
        </Entry>
        <Entry>
            <Key>W</Key>
            <Down>PANEL_HUD_NEXT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+D</Key>
            <Down>YAW_DAMPER_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+G</Key>
            <Down>AUTO_THROTTLE_TO_GA</Down>
        </Entry>
        <Entry>
            <Key>O</Key>
            <Down>SLING_PICKUP_RELEASE</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+V</Key>
            <Down>VOR_OBS</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+L</Key>
            <Down>TOGGLE_AIRCRAFT_LABELS</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+X</Key>
            <Down>ANTIDETONATION_TANK_VALVE_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+F4</Key>
            <Down>PROP_PITCH_LO</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_4</Key>
            <Down>VIEW_LEFT</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>VK_SLASH</Key>
            <Down>SPOILERS_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+K</Key>
            <Down>JOYSTICK_CALIBRATE</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+H</Key>
            <Down>PITOT_HEAT_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>T</Key>
            <Down>XPNDR</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Backspace</Key>
            <Down>EYEPOINT_FORWARD</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+B</Key>
            <Down>ROTOR_BRAKE</Down>
        </Entry>
        <Entry>
            <Key>R</Key>
            <Down>SIM_RATE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+4</Key>
            <Down>RADIO_DME1_IDENT_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>B</Key>
            <Down>BAROMETRIC</Down>
        </Entry>
        <Entry>
            <Key>CTRL+L</Key>
            <Down>LANDING_LIGHTS_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>D</Key>
            <Down>HEADING_GYRO_SET</Down>
        </Entry>
        <Entry>
            <Key>VK_SCROLL</Key>
            <Down>ATC</Down>
        </Entry>
        <Entry>
            <Key>VK_TILDE</Key>
            <Down>ATC</Down>
        </Entry>
        <Entry>
            <Key>CTRL+U</Key>
            <Down>HOIST_DEPLOY_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+R</Key>
            <Down>AP_AIRSPEED_HOLD</Down>
        </Entry>
        <Entry>
            <Key>CTRL+P</Key>
            <Down>MP_PAUSE_SESSION</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Tab</Key>
            <Down>NEXT_VIEW</Down>
        </Entry>
        <Entry>
            <Key>F3</Key>
            <Down>THROTTLE_INCR_SMALL</Down>
        </Entry>
        <Entry>
            <Key>Z</Key>
            <Down>AP_MASTER</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+VK_PERIOD</Key>
            <Down>ROTOR_CLUTCH_SWITCH_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Num_9</Key>
            <Down>VIEW_FORWARD_RIGHT_UP</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_9+Num_5</Key>
            <Down>VIEW_FORWARD_RIGHT_UP</Down>
            <Up>VIEW_FORWARD_RIGHT_UP</Up>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+T</Key>
            <Down>VIEW_PANEL_ALPHA_SELECT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+VK_RBRACKET</Key>
            <Down>MP_CHAT</Down>
        </Entry>
        <Entry>
            <Key>F7</Key>
            <Down>FLAPS_INCR</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Num_0</Key>
            <Down>RUDDER_TRIM_LEFT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Num_5</Key>
            <Down>VIEW_UP</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>L</Key>
            <Down>ALL_LIGHTS_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+D</Key>
            <Down>RELEASE_DROPPABLE_OBJECTS</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_3</Key>
            <Down>VIEW_REAR_RIGHT</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_2+Num_6</Key>
            <Down>VIEW_REAR_RIGHT</Down>
            <Up>VIEW_REAR_RIGHT</Up>
        </Entry>
        <Entry>
            <Key>CTRL+Num_2</Key>
            <Down>VIEW_REAR_UP</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_2+Num_5</Key>
            <Down>VIEW_REAR_UP</Down>
            <Up>VIEW_REAR_UP</Up>
        </Entry>
        <Entry>
            <Key>C</Key>
            <Down>COM_RADIO</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+C</Key>
            <Down>DEC_COWL_FLAPS</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+VK_PLUS</Key>
            <Down>PLUS_SHIFT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+VK_MINUS</Key>
            <Down>VIEW_CHASE_DISTANCE_SUB</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+A</Key>
            <Down>ADF</Down>
        </Entry>
        <Entry>
            <Key>F4</Key>
            <Down>THROTTLE_FULL</Down>
        </Entry>
        <Entry>
            <Key>CTRL+1</Key>
            <Down>RADIO_VOR1_IDENT_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>Num_9</Key>
            <Down>INCREASE_THROTTLE</Down>
        </Entry>
        <Entry>
            <Key>Enter</Key>
            <Down>MP_ACTIVATE_CHAT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+R</Key>
            <Down>AIRSPEED_BUG_SELECT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+3</Key>
            <Down>MARKER_SOUND_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+VK_COMMA</Key>
            <Down>ROTOR_GOV_SWITCH_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+A</Key>
            <Down>AP_APR_HOLD</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+P</Key>
            <Down>TOGGLE_PUSHBACK</Down>
        </Entry>
        <Entry>
            <Key>F1</Key>
            <Down>THROTTLE_CUT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+O</Key>
            <Down>AP_LOC_HOLD</Down>
        </Entry>
        <Entry>
            <Key>CTRL+VK_SEMICOLON</Key>
            <Down>SITUATION_RESET</Down>
        </Entry>
        <Entry>
            <Key>CTRL+F</Key>
            <Down>TOGGLE_FLIGHT_DIRECTOR</Down>
        </Entry>
        <Entry>
            <Key>K</Key>
            <Down>HOIST_SWITCH_RETRACT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Num_1</Key>
            <Down>VIEW_REAR_LEFT_UP</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_1+Num_5</Key>
            <Down>VIEW_REAR_LEFT_UP</Down>
            <Up>VIEW_REAR_LEFT_UP</Up>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+Num_2</Key>
            <Down>LANDING_LIGHT_DOWN</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+F1</Key>
            <Down>MIXTURE_LEAN</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+1</Key>
            <Down>PANEL_1</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+2</Key>
            <Down>PANEL_2</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+3</Key>
            <Down>PANEL_3</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+4</Key>
            <Down>PANEL_4</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+5</Key>
            <Down>PANEL_5</Down>
        </Entry>
        <Entry>
            <Key>VK_PLUS</Key>
            <Down>PLUS</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+6</Key>
            <Down>PANEL_6</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+L</Key>
            <Down>PANEL_LIGHTS_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+7</Key>
            <Down>PANEL_7</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+8</Key>
            <Down>PANEL_8</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+9</Key>
            <Down>PANEL_9</Down>
        </Entry>
        <Entry>
            <Key>N</Key>
            <Down>NAV_RADIO</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Num_7</Key>
            <Down>VIEW_FORWARD_LEFT_UP</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_7+Num_5</Key>
            <Down>VIEW_FORWARD_LEFT_UP</Down>
            <Up>VIEW_FORWARD_LEFT_UP</Up>
        </Entry>
        <Entry>
            <Key>Num_6</Key>
            <Down>AILERONS_RIGHT</Down>
        </Entry>
        <Entry>
            <Key>Num_2</Key>
            <Down>ELEV_UP</Down>
        </Entry>
        <Entry>
            <Key>Q</Key>
            <Down>SOUND_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>H</Key>
            <Down>ANTI_ICE_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>VK_SUBTRACT</Key>
            <Down>BRAKES_RIGHT</Down>
        </Entry>
        <Entry>
            <Key>F2</Key>
            <Down>THROTTLE_DECR</Down>
        </Entry>
        <Entry>
            <Key>VK_DIVIDE</Key>
            <Down>VIEW</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+9</Key>
            <Down>CENTER_NT361_CHECK</Down>
        </Entry>
        <Entry>
            <Key>VK_PERIOD</Key>
            <Down>BRAKES</Down>
        </Entry>
        <Entry>
            <Key>CTRL+VK_SLASH</Key>
            <Down>INVOKE_HELP</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+VK_SLASH</Key>
            <Down>INVOKE_HELP</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_1</Key>
            <Down>VIEW_REAR_LEFT</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_2+Num_4</Key>
            <Down>VIEW_REAR_LEFT</Down>
            <Up>VIEW_REAR_LEFT</Up>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+Y</Key>
            <Down>TOW_PLANE_REQUEST</Down>
        </Entry>
        <Entry>
            <Key>Num_3</Key>
            <Down>DECREASE_THROTTLE</Down>
        </Entry>
        <Entry>
            <Key>VK_RBRACKET</Key>
            <Down>CLOSE_VIEW</Down>
        </Entry>
        <Entry>
            <Key>U</Key>
            <Down>POINT_OF_INTEREST_TOGGLE_POINTER</Down>
        </Entry>
        <Entry>
            <Key>1</Key>
            <Down>SELECT_1</Down>
        </Entry>
        <Entry>
            <Key>2</Key>
            <Down>SELECT_2</Down>
        </Entry>
        <Entry>
            <Key>3</Key>
            <Down>SELECT_3</Down>
        </Entry>
        <Entry>
            <Key>4</Key>
            <Down>SELECT_4</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+VK_MINUS</Key>
            <Down>MINUS_SHIFT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+Q</Key>
            <Down>VIEW_ALWAYS_PAN_UP</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Z</Key>
            <Down>READOUTS_FLIGHT</Down>
        </Entry>
        <Entry>
            <Key>X</Key>
            <Down>FREQUENCY_SWAP</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Q</Key>
            <Down>VIEW_ALWAYS_PAN_DOWN</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_7</Key>
            <Down>VIEW_FORWARD_LEFT</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_4+Num_8</Key>
            <Down>VIEW_FORWARD_LEFT</Down>
            <Up>VIEW_FORWARD_LEFT</Up>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+Enter</Key>
            <Down>EYEPOINT_RIGHT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+N</Key>
            <Down>AP_NAV1_HOLD</Down>
        </Entry>
        <Entry>
            <Key>CTRL+H</Key>
            <Down>AP_HDG_HOLD</Down>
        </Entry>
        <Entry>
            <Key>F8</Key>
            <Down>FLAPS_DOWN</Down>
        </Entry>
        <Entry>
            <Key>CTRL+5</Key>
            <Down>RADIO_ADF_IDENT_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+H</Key>
            <Down>HEADING_BUG_SELECT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Z</Key>
            <Down>AP_ALT_HOLD</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+VK_SLASH</Key>
            <Down>SPOILERS_ARM_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>Num_5</Key>
            <Down>CENTER_AILER_RUDDER</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_9</Key>
            <Down>VIEW_FORWARD_RIGHT</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_6+Num_8</Key>
            <Down>VIEW_FORWARD_RIGHT</Down>
            <Up>VIEW_FORWARD_RIGHT</Up>
        </Entry>
        <Entry>
            <Key>CTRL+F2</Key>
            <Down>PROP_PITCH_DECR</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+Num_8</Key>
            <Down>LANDING_LIGHT_UP</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+K</Key>
            <Down>POINT_OF_INTEREST_CYCLE_PREVIOUS</Down>
        </Entry>
        <Entry>
            <Key>CTRL+T</Key>
            <Down>AP_ATT_HOLD</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+C</Key>
            <Down>NITROUS_TANK_VALVE_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Num_6</Key>
            <Down>AILERON_TRIM_RIGHT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+E</Key>
            <Down>ENGINE_AUTO_START</Down>
        </Entry>
        <Entry>
            <Key>Esc</Key>
            <Down>USER_INTERRUPT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+Num_5</Key>
            <Down>LANDING_LIGHT_HOME</Down>
        </Entry>
        <Entry>
            <Key>F6</Key>
            <Down>FLAPS_DECR</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+M</Key>
            <Down>TOGGLE_MASTER_BATTERY_ALTERNATOR</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+I</Key>
            <Down>YAXIS_INVERT_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+W</Key>
            <Down>PANEL_HUD_PREVIOUS</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Enter</Key>
            <Down>EYEPOINT_UP</Down>
        </Entry>
        <Entry>
            <Key>F</Key>
            <Down>DME</Down>
        </Entry>
        <Entry>
            <Key>CTRL+F1</Key>
            <Down>PROP_PITCH_HI</Down>
        </Entry>
        <Entry>
            <Key>VK_PAUSE</Key>
            <Down>PAUSE_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>P</Key>
            <Down>PAUSE_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+F2</Key>
            <Down>MIXTURE_DECR</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Num_3</Key>
            <Down>VIEW_REAR_RIGHT_UP</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_3+Num_5</Key>
            <Down>VIEW_REAR_RIGHT_UP</Down>
            <Up>VIEW_REAR_RIGHT_UP</Up>
        </Entry>
        <Entry>
            <Key>Caps_Lock</Key>
            <Down>MP_VOICE_CAPTURE_START</Down>
            <Up>MP_VOICE_CAPTURE_STOP</Up>
        </Entry>
        <Entry>
            <Key>SHIFT+Q</Key>
            <Down>TOGGLE_TAIL_HOOK_HANDLE</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+U</Key>
            <Down>TOGGLE_LAUNCH_BAR_SWITCH</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Backspace</Key>
            <Down>EYEPOINT_DOWN</Down>
        </Entry>
        <Entry>
            <Key>CTRL+VK_PLUS</Key>
            <Down>VIEW_CHASE_DISTANCE_ADD</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_6</Key>
            <Down>VIEW_RIGHT</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>Num_4</Key>
            <Down>AILERONS_LEFT</Down>
        </Entry>
        <Entry>
            <Key>Num_8</Key>
            <Down>ELEV_DOWN</Down>
        </Entry>
        <Entry>
            <Key>CTRL+B</Key>
            <Down>AP_BC_HOLD</Down>
        </Entry>
        <Entry>
            <Key>CTRL+V</Key>
            <Down>AP_WING_LEVELER</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_Del</Key>
            <Down>PAN_RESET</Down>
        </Entry>
        <Entry>
            <Key>F24</Key>
            <Down>RUDDER_RIGHT</Down>
        </Entry>
        <Entry>
            <Key>F9</Key>
            <Down>VIEW_CAMERA_SELECT_1</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Space</Key>
            <Down>EYEPOINT_RESET</Down>
        </Entry>
        <Entry>
            <Key>F10</Key>
            <Down>VIEW_CAMERA_SELECT_2</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Y</Key>
            <Down>MOUSE_AS_YOKE_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+A</Key>
            <Down>PREV_SUB_VIEW</Down>
        </Entry>
        <Entry>
            <Key>F11</Key>
            <Down>VIEW_CAMERA_SELECT_3</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+F12</Key>
            <Down>VIEW_CAMERA_SELECT_4</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Num_4</Key>
            <Down>AILERON_TRIM_LEFT</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_0</Key>
            <Down>SNAP_TO_PANEL</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Space</Key>
            <Down>TAKEOFF_ASSIST_FIRE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+D</Key>
            <Down>FUEL_DUMP_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>Num_0</Key>
            <Down>RUDDER_LEFT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+Num_4</Key>
            <Down>LANDING_LIGHT_LEFT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+VK_TILDE</Key>
            <Down>SIMUI_WINDOW_HIDESHOW</Down>
        </Entry>
        <Entry>
            <Key>F5</Key>
            <Down>FLAPS_UP</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+E</Key>
            <Down>TOGGLE_AIRCRAFT_EXIT</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_5</Key>
            <Down>VIEW_DOWN</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>SHIFT+VK_RBRACKET</Key>
            <Down>NEW_MAP</Down>
        </Entry>
        <Entry>
            <Key>S</Key>
            <Down>VIEW_MODE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+X</Key>
            <Down>VIRTUAL_COPILOT_ACTION</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_2</Key>
            <Down>VIEW_REAR</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>CTRL+J</Key>
            <Down>TOGGLE_JETWAY</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+Z</Key>
            <Down>ALTITUDE_BUG_SELECT</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+O</Key>
            <Down>MP_PLAYER_CYCLE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+F4</Key>
            <Down>MIXTURE_RICH</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Num_8</Key>
            <Down>VIEW_FORWARD</Down>
            <Up>VIEW_RESET</Up>
        </Entry>
        <Entry>
            <Key>SHIFT+F4</Key>
            <Down>TOGGLE_AFTERBURNER</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Scroll_Lock</Key>
            <Down>ABORT</Down>
        </Entry>
    </SimControls.Map>
    <SimControls.Map>
        <Name>KEYBOARD_SLEW</Name>
        <Entry>
            <Key>F7</Key>
            <Down>SLEW_PITCH_DN_SLOW</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Enter</Key>
            <Down>EYEPOINT_BACK</Down>
        </Entry>
        <Entry>
            <Key>A</Key>
            <Down>NEXT_SUB_VIEW</Down>
        </Entry>
        <Entry>
            <Key>Space</Key>
            <Down>MOUSE_LOOK_TOGGLE</Down>
            <DownVal>1</DownVal>
            <Up>MOUSE_LOOK_TOGGLE</Up>
            <UpVal>2</UpVal>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+D</Key>
            <Down>MOUSE_LOOK_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>Num_1</Key>
            <Down>SLEW_HEADING_MINUS</Down>
        </Entry>
        <Entry>
            <Key>F4</Key>
            <Down>SLEW_ALTIT_UP_FAST</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+Backspace</Key>
            <Down>EYEPOINT_LEFT</Down>
        </Entry>
        <Entry>
            <Key>Y</Key>
            <Down>SLEW_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>Num_9</Key>
            <Down>SLEW_BANK_PLUS</Down>
        </Entry>
        <Entry>
            <Key>9</Key>
            <Down>SLEW_PITCH_PLUS</Down>
        </Entry>
        <Entry>
            <Key>Z</Key>
            <Down>SLEW_ALTIT_MINUS</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+L</Key>
            <Down>TOGGLE_AIRCRAFT_LABELS</Down>
        </Entry>
        <Entry>
            <Key>F8</Key>
            <Down>SLEW_PITCH_DN_FAST</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Backspace</Key>
            <Down>EYEPOINT_FORWARD</Down>
        </Entry>
        <Entry>
            <Key>Num_8</Key>
            <Down>SLEW_AHEAD_PLUS</Down>
        </Entry>
        <Entry>
            <Key>Q</Key>
            <Down>SLEW_ALTIT_PLUS</Down>
        </Entry>
        <Entry>
            <Key>Num_7</Key>
            <Down>SLEW_BANK_MINUS</Down>
        </Entry>
        <Entry>
            <Key>Num_6</Key>
            <Down>SLEW_RIGHT</Down>
        </Entry>
        <Entry>
            <Key>F6</Key>
            <Down>SLEW_PITCH_FREEZE</Down>
        </Entry>
        <Entry>
            <Key>Num_5</Key>
            <Down>SLEW_FREEZE</Down>
        </Entry>
        <Entry>
            <Key>F1</Key>
            <Down>SLEW_ALTIT_DN_FAST</Down>
        </Entry>
        <Entry>
            <Key>F2</Key>
            <Down>SLEW_ALTIT_FREEZE</Down>
        </Entry>
        <Entry>
            <Key>CTRL+Space</Key>
            <Down>SLEW_RESET</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+Enter</Key>
            <Down>EYEPOINT_RIGHT</Down>
        </Entry>
        <Entry>
            <Key>Num_2</Key>
            <Down>SLEW_AHEAD_MINUS</Down>
        </Entry>
        <Entry>
            <Key>Num_3</Key>
            <Down>SLEW_HEADING_PLUS</Down>
        </Entry>
        <Entry>
            <Key>CTRL+SHIFT+I</Key>
            <Down>YAXIS_INVERT_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Enter</Key>
            <Down>EYEPOINT_UP</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Backspace</Key>
            <Down>EYEPOINT_DOWN</Down>
        </Entry>
        <Entry>
            <Key>F3</Key>
            <Down>SLEW_ALTIT_UP_SLOW</Down>
        </Entry>
        <Entry>
            <Key>F5</Key>
            <Down>SLEW_PITCH_UP_FAST</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+X</Key>
            <Down>MOUSE_AS_YOKE_TOGGLE</Down>
        </Entry>
        <Entry>
            <Key>Num_4</Key>
            <Down>SLEW_LEFT</Down>
        </Entry>
        <Entry>
            <Key>0</Key>
            <Down>SLEW_PITCH_MINUS</Down>
        </Entry>
        <Entry>
            <Key>SHIFT+Z</Key>
            <Down>READOUTS_SLEW</Down>
        </Entry>
    </SimControls.Map>
    <SimControls.Map>
        <Name>Mouse Yoke</Name>
        <Axis>
            <AxName>XAxis</AxName>
            <Index>0</Index>
            <AxEvent>AXIS_AILERONS_SET</AxEvent>
            <AxScale>64</AxScale>
            <AxNull>36</AxNull>
        </Axis>
        <Axis>
            <AxName>YAxis</AxName>
            <Index>1</Index>
            <AxEvent>AXIS_ELEVATOR_SET</AxEvent>
            <AxScale>64</AxScale>
            <AxNull>36</AxNull>
        </Axis>
        <Entry>
            <Index>0</Index>
            <Down>BRAKES</Down>
            <DownRpt>1</DownRpt>
        </Entry>
        <Entry>
            <Index>2</Index>
            <Down>SLEW_RESET</Down>
        </Entry>
        <Entry>
            <Index>3</Index>
            <Down>FLAPS_INCR</Down>
        </Entry>
        <Entry>
            <Index>4</Index>
            <Down>FLAPS_DECR</Down>
        </Entry>
        <Entry>
            <Index>6</Index>
            <Down>THROTTLE_INCR</Down>
        </Entry>
        <Entry>
            <Index>7</Index>
            <Down>THROTTLE_DECR</Down>
        </Entry>
    </SimControls.Map>
    <SimControls.Map>
        <Name>Mouse Yoke SLEW</Name>
        <Axis>
            <AxName>XAxis</AxName>
            <Index>0</Index>
            <AxEvent>AXIS_SLEW_SIDEWAYS_SET</AxEvent>
            <AxScale>64</AxScale>
            <AxNull>36</AxNull>
        </Axis>
        <Axis>
            <AxName>YAxis</AxName>
            <Index>1</Index>
            <AxEvent>AXIS_SLEW_AHEAD_SET</AxEvent>
            <AxScale>64</AxScale>
            <AxNull>36</AxNull>
        </Axis>
        <Entry>
            <Index>0</Index>
            <Down>SLEW_RESET</Down>
        </Entry>
        <Entry>
            <Index>2</Index>
            <Down>SLEW_FREEZE</Down>
        </Entry>
        <Entry>
            <Index>3</Index>
            <Down>SLEW_ALTIT_MINUS</Down>
            <DownRpt>1</DownRpt>
        </Entry>
        <Entry>
            <Index>4</Index>
            <Down>SLEW_ALTIT_PLUS</Down>
            <DownRpt>1</DownRpt>
        </Entry>
        <Entry>
            <Index>6</Index>
            <Down>SLEW_PITCH_DN_SLOW</Down>
            <Up>SLEW_FREEZE</Up>
        </Entry>
        <Entry>
            <Index>7</Index>
            <Down>SLEW_PITCH_UP_SLOW</Down>
            <Up>SLEW_FREEZE</Up>
        </Entry>
    </SimControls.Map>
    <SimControls.Map>
        <Name>Mouse Look</Name>
        <Axis>
            <AxName>XAxis</AxName>
            <Index>0</Index>
            <AxEvent>AXIS_PAN_HEADING</AxEvent>
            <AxScale>64</AxScale>
            <AxNull>36</AxNull>
        </Axis>
        <Axis>
            <AxName>YAxis</AxName>
            <Index>1</Index>
            <AxEvent>AXIS_PAN_PITCH</AxEvent>
            <AxScale>-64</AxScale>
            <AxNull>36</AxNull>
        </Axis>
        <Entry>
            <Index>0</Index>
            <Down>VIEW_RESET</Down>
        </Entry>
        <Entry>
            <Index>2</Index>
            <Down>EYEPOINT_RESET</Down>
        </Entry>
        <Entry>
            <Index>3</Index>
            <Down>EYEPOINT_UP</Down>
            <DownRpt>1</DownRpt>
        </Entry>
        <Entry>
            <Index>4</Index>
            <Down>EYEPOINT_DOWN</Down>
        </Entry>
        <Entry>
            <Index>6</Index>
            <Down>ZOOM_OUT</Down>
        </Entry>
        <Entry>
            <Index>7</Index>
            <Down>ZOOM_IN</Down>
        </Entry>
    </SimControls.Map>
    <SimControls.Map>
        <Name>Mouse Look SLEW</Name>
        <Axis>
            <AxName>XAxis</AxName>
            <Index>0</Index>
            <AxEvent>AXIS_PAN_HEADING</AxEvent>
            <AxScale>64</AxScale>
            <AxNull>36</AxNull>
        </Axis>
        <Axis>
            <AxName>YAxis</AxName>
            <Index>1</Index>
            <AxEvent>AXIS_PAN_PITCH</AxEvent>
            <AxScale>-64</AxScale>
            <AxNull>36</AxNull>
        </Axis>
        <Entry>
            <Index>0</Index>
            <Down>SLEW_RESET</Down>
        </Entry>
        <Entry>
            <Index>2</Index>
            <Down>SLEW_FREEZE</Down>
        </Entry>
        <Entry>
            <Index>3</Index>
            <Down>SLEW_ALTIT_MINUS</Down>
            <DownRpt>1</DownRpt>
        </Entry>
        <Entry>
            <Index>4</Index>
            <Down>SLEW_ALTIT_PLUS</Down>
            <DownRpt>1</DownRpt>
        </Entry>
        <Entry>
            <Index>6</Index>
            <Down>SLEW_PITCH_DN_SLOW</Down>
            <Up>SLEW_FREEZE</Up>
        </Entry>
        <Entry>
            <Index>7</Index>
            <Down>SLEW_PITCH_UP_SLOW</Down>
            <Up>SLEW_FREEZE</Up>
        </Entry>
    </SimControls.Map>
    <SimControls.Map>
        <Name>Xbox 360 Controller #1</Name>
    </SimControls.Map>
    <SimControls.Map>
        <Name>Xbox 360 Controller SLEW  #1</Name>
    </SimControls.Map>
    <SimControls.Map>
        <Name>vJoy Device{$vJoyDeviceGuid}</Name>
        <Axis>
            <AxName>XAxis</AxName>
            <Index>0</Index>
            <AxEvent>AXIS_AILERONS_SET</AxEvent>
            <AxScale>127</AxScale>
            <AxNull>36</AxNull>
        </Axis>
        <Axis>
            <AxName>YAxis</AxName>
            <Index>1</Index>
            <AxEvent>AXIS_ELEVATOR_SET</AxEvent>
            <AxScale>127</AxScale>
            <AxNull>36</AxNull>
        </Axis>
        <Axis>
            <AxName>ZAxis</AxName>
            <Index>2</Index>
            <AxEvent>AXIS_THROTTLE_SET</AxEvent>
            <AxScale>127</AxScale>
        </Axis>
        <Axis>
            <AxName>RxAxis</AxName>
            <Index>3</Index>
            <AxEvent>AXIS_PAN_HEADING</AxEvent>
            <AxScale>127</AxScale>
        </Axis>
        <Axis>
            <AxName>RyAxis</AxName>
            <Index>4</Index>
            <AxEvent>AXIS_PAN_PITCH</AxEvent>
            <AxScale>127</AxScale>
        </Axis>
        <Axis>
            <AxName>RzAxis</AxName>
            <Index>5</Index>
            <AxEvent>AXIS_RUDDER_SET</AxEvent>
            <AxScale>127</AxScale>
            <AxNull>50</AxNull>
        </Axis>
        <Axis>
            <AxName>Slider</AxName>
            <Index>6</Index>
            <AxEvent>AXIS_PROPELLER_SET</AxEvent>
            <AxScale>127</AxScale>
        </Axis>
        <Axis>
            <AxName>NULL</AxName>
            <Index>7</Index>
            <AxEvent>AXIS_MIXTURE_SET</AxEvent>
            <AxScale>127</AxScale>
        </Axis>
        <Entry>
            <Index>0</Index>
            <Down>BRAKES_LEFT</Down>
            <DownRpt>1</DownRpt>
        </Entry>
        <Entry>
            <Index>1</Index>
            <Down>BRAKES_RIGHT</Down>
            <DownRpt>1</DownRpt>
        </Entry>
    </SimControls.Map>
    <SimControls.Map>
        <Name>vJoy Device SLEW {$vJoyDeviceGuid}</Name>
        <Axis>
            <AxName>XAxis</AxName>
            <Index>0</Index>
            <AxEvent>AXIS_SLEW_SIDEWAYS_SET</AxEvent>
            <AxScale>127</AxScale>
            <AxNull>36</AxNull>
        </Axis>
        <Axis>
            <AxName>YAxis</AxName>
            <Index>1</Index>
            <AxEvent>AXIS_SLEW_AHEAD_SET</AxEvent>
            <AxScale>127</AxScale>
            <AxNull>36</AxNull>
        </Axis>
        <Axis>
            <AxName>ZAxis</AxName>
            <Index>2</Index>
            <AxEvent>AXIS_SLEW_ALT_SET</AxEvent>
            <AxScale>-127</AxScale>
            <AxNull>36</AxNull>
        </Axis>
        <Axis>
            <AxName>RzAxis</AxName>
            <Index>5</Index>
            <AxEvent>AXIS_SLEW_HEADING_SET</AxEvent>
            <AxScale>127</AxScale>
            <AxNull>36</AxNull>
        </Axis>
    </SimControls.Map>

"@
    $gamepadDevices | ForEach-Object {
        $gamepadDeviceName = [System.Net.WebUtility]::HtmlEncode($_.InstanceName)
        $gamepadDeviceGuid = Get-DeviceGuid $_
        $standardXmlContent += @"
    <SimControls.Map>
        <Name>$gamepadDeviceName{$gamepadDeviceGuid}</Name>
    </SimControls.Map>

"@
    }
    $standardXmlContent += '</SimBase.Document>'

    Set-Content -Path $standardXmlFile -Value $standardXmlContent
    Write-Output "Wrote file: $standardXmlFile"
} catch {
    Write-Output "Error: Could not write file: $fsxCfgFile"
    Exit 1
}

$fsxCfgFile = "$fsxDir\fsx.CFG"
if (-not (Test-Path $fsxCfgFile -PathType Leaf)) {
    Write-Output "Error: file '$fsxCfgFile' does not exist"
    Exit 1
}

try {
    $fsxCfgContent = (Get-Content -Raw $fsxCfgFile) -replace '\[CONTROLS]\r\n[^\[]*'
    if ($fsxCfgContent -notmatch "`r?`n$") {
        $fsxCfgContent += "`r`n"
    }
    $fsxCfgContent += @"
[CONTROLS]
Controls_Default=Standard
Controls_Current=Standard
force_master_gain=10000
force_stick_force_enabled=0
force_stick_shaker_enabled=0
force_gear_bump_enabled=0
force_crash_enabled=0
force_ground_bumps_enabled=0
force_master_enabled=0
KBDAIL=64
KBDELEV=64
KBDRUD=64
"@

    Set-Content -Path $fsxCfgFile -Value $fsxCfgContent
    Write-Output "Updated file: $fsxCfgFile"
} catch {
    Write-Output "Error: Could not update file: $fsxCfgFile"
    Exit 1
}

Write-Output "`nFlight Simulator X is now fully configured!"
Exit 0