on:
  push:
    branches:
      - master

jobs:
  psscriptanalyzer:
    runs-on: ubuntu-latest
    permissions:
          security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f # v1.1
        with:
          path: configs
          recurse: true
      - name: Upload SARIF Results
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4
        with:
          sarif_file: results.sarif
