on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ControllerBuddy-Profiles
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          path: ControllerBuddy-Profiles
          fetch-depth: 0
          persist-credentials: false
      - name: Checkout ControllerBuddy
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          repository: bwRavencl/ControllerBuddy
          path: ControllerBuddy
          fetch-depth: 0
          persist-credentials: false
          submodules: true
      - name: Checkout ControllerBuddy-Pages
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          repository: bwRavencl/ControllerBuddy-Pages
          path: ControllerBuddy-Pages
          fetch-depth: 0
          persist-credentials: false
      - name: Install ControllerBuddy
        uses: bwRavencl/ControllerBuddy/.github/actions/run-gradle-task@master
        with:
          task: installDist -x check
          working-directory: ControllerBuddy
          upload-artifacts: false
      - name: Update Visualizations
        timeout-minutes: 3
        run: |
          export PATH="${{ github.workspace }}/ControllerBuddy/build/install/ControllerBuddy/bin:$PATH"
          rm -f ControllerBuddy-Pages/profiles/*.html
          xvfb-run -a -s '-screen 0 1024x768x24' ControllerBuddy -skipMessageDialogs &
          while [ ! -f /tmp/ControllerBuddy.lock ]
          do
            sleep 1
          done
          for file in ControllerBuddy-Profiles/*.json
          do
            xvfb-run -a -s '-screen 0 1024x768x24' ControllerBuddy -skipMessageDialogs -profile "$file" -export "ControllerBuddy-Pages/profiles/$(basename "$file" .json).html" || exit 1
          done
          xvfb-run -a -s '-screen 0 1024x768x24' ControllerBuddy -quit
      - name: Commit Files
        working-directory: ControllerBuddy-Pages
        run: |
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'
          git add profiles
          git commit -m 'chore: update profile visualizations' || echo 'Nothing to update'
      - name: Push Changes
        uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # v1
        with:
          repository: bwRavencl/ControllerBuddy-Pages
          directory: ControllerBuddy-Pages
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
