name: Update Version Branch

on:
  push:
    branches:
      - master

jobs:
  update-version-branch:
    runs-on: ubuntu-latest
    permissions:
          contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Force-Push Changes to Latest Version Branch
        run: |
          branch=$(jq -r '.["version"]' *.json | sort -Vu | tail -n 1 | tr -d '\r,\n')
          git checkout -b "$branch"
          git push -f origin "$branch"
