on:
  push:
    branches:
      - master

jobs:
  version-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Force-Push Changes to Latest Version Branch
        run: |
          branch=$(jq -r '.["version"]' *.json | sort -Vu | tail -n 1 | tr -d '\r,\n')
          git checkout -b "$branch"
          git push -f origin "$branch"
